### PR TITLE
Fixed a possible security issue.

### PR DESCRIPTION
**Pull request by Mrrraou**
Made it more readable, and fixed some typos.

### CODE REVIEW

**Comment by felipejfc** [comment]
can you use 2 spaces to indent instead of tabs?
also, I'ld like to keep the code with no semicolons

**Comment by Mrrraou** [comment]
@felipejfc Well, I don't know why you want that. Removing semicolons is not really JavaScript compliant.

**Comment by felipejfc** [comment]
yes it is, because of automatic semicolon insertion,
http://mislav.net/2010/05/semicolons/

**Comment by Mrrraou** [comment]
Oh well. Why not, then.

**Pull request closed without merging**
